### NumPy Basics

In [2]:
# Instalar y Actualiza NumPy 
# pip install numpy
# pip install numpy --upgrade

In [3]:
# Importar NumPy
import numpy as np

In [4]:
#     1     - scalar   - 0-D
# [1,2,3]   - vector   - 1-D
# |0,2,3|   - mtraix   - 2-D
# |4,9,7|

In [5]:
# Crear un ARRAY con 1-D
array_a = np.array([1,2,3]) # 1-D

# Mostramos el contenido
array_a

array([1, 2, 3])

In [6]:
# Crear un ARRAY con 2-D
array_b=np.array([[1,2,3],[4,5,6]])
# Mostramos el contenido
array_b

array([[1, 2, 3],
       [4, 5, 6]])

### Ndarrays

In [7]:
# Ndarrays: puede almacenar múltiples valores númericos, para operaciones computacionales
# ndarrays = N-Dimensional array

In [8]:
# Creamos un ARRAY
array = np.array([1,2,3])
# Mostramos el contenido
array

array([1, 2, 3])

In [9]:
# Tipo de dato
type(array)
# es de tipo ndarray

numpy.ndarray

In [10]:
#Mostrar el tamaño del ARRAY
array.shape
#Tenemos un ARRAY unidimensional

(3,)

In [11]:
# Crear un ARRAY con 2-D
array_b=np.array([[7,8,9],[10,11,12]])
# Mostramos el contenido
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
# Tipo de dato
type(array_b)
# es de tipo ndarray

numpy.ndarray

In [13]:
# Mostrar el tamaño del ARRAY
array_b.shape
#(2 filas, 3 valores o columnas)

(2, 3)

In [14]:
# Obtener filas o columnas de un ARRAY
print(array_b.shape[0]) # filas
print(array_b.shape[1]) # columnas

2
3


### Arrays vs. Listas 

In [15]:
# Definimos una LISTA
list_a = [1,2,3,4,5,6]
# Mostramos el contenido
list_a

[1, 2, 3, 4, 5, 6]

In [16]:
# Longitud de la LISTA
len(list_a)

6

In [17]:
# Definir una LISTA de LISTA
list_b=[[1,2,3],[4,5,6]]
# Mostramos el contenido
list_b

[[1, 2, 3], [4, 5, 6]]

In [18]:
# Longitud de la LISTA
len(list_b) # La lista tiene una longitud de 2 listas dentro de la misma.

2

In [19]:
# Ver el tipo de dato
type(list_b)

list

In [20]:
# Ahora creamos un ARRAY a partir de la LISTA
array_a=np.array(list_b)
# Mostrar contenido
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Verificamos el tipo de dato
type(array_a)

numpy.ndarray

In [22]:
# Mostrar LISTA
print(list_b)
# La lista muestra todo en una sola línea

[[1, 2, 3], [4, 5, 6]]


In [23]:
# Mostrar ARRAY
print(array_a)
# El array muestra el contenido en 2 filas y 3 columnas

[[1 2 3]
 [4 5 6]]


In [24]:
# Creamos una LISTA y ARRAY a partir de las anteriores
new_list= list_b[0] + list_b[1]
new_array= array_a[0] + array_a[1]

In [25]:
# Imprimir LISTA
print(new_list)

[1, 2, 3, 4, 5, 6]


In [26]:
# Imprimir ARRAY
print(new_array)

[5 7 9]


In [27]:
# Observamos que en la LISTA concatena los valores y
# en el ARRAY suma los valores de [0][0] + [0][1] y así sucesivamente

In [28]:
# Sacar la RAÍZ CUADRADA
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Indexing 

In [29]:
# Son como coordenadas que nos ayudan a navegar por el ARRAY.
# Son números enteros, comenzando desde 0 la primera posición

In [30]:
# Definimos un ARRAY bidimensional 2-D
array_a = np.array([[1,2,3],[4,5,6]])
# Mostramos el contenido
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Especificar Valores
array_a[0]
# Nos muestra la primera fila del ARRAY

array([1, 2, 3])

In [32]:
array_a[1]
# Nos muestra la segunda fila del ARRAY

array([4, 5, 6])

In [33]:
# Para obtener un valor individual
array_a[0][0]  # o array_a[0,0]
# Nos muestra el primer valor de la primera fila

1

In [34]:
array_a[0][2]
# Nos muestra el tercer valor de la primera fila

3

In [35]:
array_a[1][1]
# Nos muestra el segundo valor de la segunda fila

5

In [36]:
# Obtener valores de una columna
array_a[:,0]
# Muestra todos los valores de la primera columna

array([1, 4])

In [37]:
# índices negativos
array_b=np.array([1,2,3])
# Mostrar el contenido
array_b

array([1, 2, 3])

In [38]:
array_b[-1]
# Muestra el primer valor de la fila partiendo de la derecha

3

In [39]:
array_b[-3]
# Muestra el tercer valor de la fila partiendo de la derecha

1

### Asignar Valores 

In [40]:
# Creamos un ARRAY
array_a = np.array([[3,4,5,6],[7,8,9,10]])
# Mostramos el contenido
array_a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [41]:
# Cambiar el valor del ARRAY a través de la posición
array_a[0,3]=2
# Cambios el valor del cuarto valor de la fila 1

array_a # Cambiamos el 6 por el 2

array([[ 3,  4,  5,  2],
       [ 7,  8,  9, 10]])

In [42]:
# Cambiar valores de una FILA
array_a[0] = [1,2,3,4]
array_a # Cambios la fila [3,4,5,2] por [1,2,3,4]

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [43]:
# Cambiar valores de la COLUMNA
array_a[:,0] = [5,6]
array_a # Cambios la columna [1,7] por [5,6]

array([[ 5,  2,  3,  4],
       [ 6,  8,  9, 10]])

### Propiedades Elementales 

In [44]:
# Creamos el primer ARRAY
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [45]:
# Creamos el segundo ARRAY
array_b = np.array([[4,5,6],[7,8,9]])
array_b

array([[4, 5, 6],
       [7, 8, 9]])

In [46]:
# 1. Al realizar una operación matemática lo estás haciendo a cada elemento del ARRAY
# 2. Los ARRAYS deben tener la misma longitud

In [47]:
array_a + 2  # Se sumó 2 a cada elemento del ARRAY

array([3, 4, 5])

In [48]:
# Operación entre 2 ARRAY
array_a + array_b[0] # Se sumó el array_a y la primera fila del array_b

array([5, 7, 9])

In [49]:
array_a * array_b[0] # Se multiplicó el array_a y la primera fila del array_b

array([ 4, 10, 18])

In [50]:
array_a + array_b # Suma el array_a a cada dimensión del array_b

array([[ 5,  7,  9],
       [ 8, 10, 12]])

### Tipos de datos admintidos en NumPy

In [51]:
# Definimos un ARRAY bidimesional
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
# Ahora definimos el tipo de dato al ARRAY - FLOAT
array_a=np.array([[1,2,3],[4,5,6]], dtype='float32') #De tipo float32
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [53]:
# Otra manera de asignar el tipo de dato del ARRAY - FLOAT
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.float32) #De tipo float32
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [54]:
# Asignar tipo de datos COMPLEJOS
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.complex64) #De tipo complex64
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [55]:
# Asignar tipo de datos BOOLEAN
array_a=np.array([[1,2,3],[4,0,6]], dtype=np.bool_) #De tipo bool
# Será verdadero si el valor > 0 y falso si es 0
array_a

array([[ True,  True,  True],
       [ True, False,  True]])

In [56]:
# Asignar tipo de datos STRING
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.str_) #De tipo string
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

### Funciones NumPy 

In [57]:
# BROADCASTING
# Hace un redimensionamiento del ARRAY para adecuarlo a otro
# Ejemplo: [1] y [1,2],[3,4], esto redimensionará a [1,1],[1,1] para que tenga las mismas dimensiones que [1,2],[3,4]

In [58]:
# Creamos un ARRAY
array_c = np.array([1,2])
array_c

array([1, 2])

In [59]:
# Creamos un segundo ARRAY
array_d = np.array([[1,2], [4,5], [7,8]])
array_d

array([[1, 2],
       [4, 5],
       [7, 8]])

In [60]:
# broadcasting:
np.add(array_c,array_d)

array([[ 2,  4],
       [ 5,  7],
       [ 8, 10]])

In [61]:
# Tyoe Casting
# Tomar un elemento del ARRAY y cambiarlo a un tipo de dato específico

In [62]:
#Cambiamos el tipo de dato de salida y el de entradas
np.add(array_c,array_d, dtype=np.float64)

array([[ 2.,  4.],
       [ 5.,  7.],
       [ 8., 10.]])

In [63]:
# AXIS
# axis= 0 : columna del array
# axis= 1 : fila del array

In [64]:
# Obtener el promedio por COLUMNA
np.mean(array_d, axis=0)

array([4., 5.])

In [65]:
# Obtener el promedio por FILA
np.mean(array_d, axis=1)

array([1.5, 4.5, 7.5])

In [66]:
# OTRAS FUNCIONES:
#np.mean(array_d)
#np.sum(array_d)

### Trabajando con Arrays

In [67]:
#Definimos un ARRAY con 2-D
matrix_a= np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [68]:
# Es el acto de crear un nuevo ARRAY tomando trozos de valores de un existente
# Es igual a "interval indexing"

In [70]:
#Obtener todas las filas y columnas
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# Obtener primera fila
matrix_a[:1]

array([[1, 2, 3]])

In [76]:
#Obtener segunda fila 2-D
matrix_a[1]

array([4, 5, 6])

In [79]:
# Obtener primera fila
matrix_a[:-1]

array([[1, 2, 3]])

In [81]:
# Obtener a partir de la segunda columna[1]
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [82]:
#Obtener desde la segunda columna pero de la segunda fila
matrix_a[1:,1:]

array([[5, 6]])

### Stepwise Slicing 

In [83]:
# Corte paso a paso representa el corte donde no toma valores consecutivos sino valores separados.

In [85]:
# Definimos un ARRAY de 3-D
matrix_b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [88]:
# Como anteriormente, obtener todo
matrix_b[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [90]:
#Ejemplo: matrix_b[inicio:final:distancia,::]
# distancia default: 1
matrix_b[::,::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [92]:
#Distancia 2, pasalo de la fila 0 a la fila 2
matrix_b[::2,::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [94]:
#Muestra las columnas 0, 2 y 4, vemos quue salta una columna
matrix_b[::,::2] #Salto de 2 en columnas

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [96]:
#Muestras las filas 0 y 2, y las columnas 0,2 y 4 
matrix_b[::2,::2] #Salto de 2 en filas y columnas

array([[ 1,  3,  5],
       [11, 13, 15]])

In [99]:
matrix_b[::-1,::2] #salto de 2 columnas e invertir el orden de valores (-1)

array([[11, 13, 15],
       [ 6,  8, 10],
       [ 1,  3,  5]])

### Conditional Slicing 

In [102]:
#Utilizaremos la misma MATRIX
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
#Obtener columna 0
matrix_b[:,0]

array([ 1,  6, 11])

In [106]:
# Obtener los valores de la columna 1 que sean mayores a 5
matrix_b[:,1] > 5

array([False,  True,  True])

In [108]:
# Valores mayores de 4 de la MATRIX
matrix_b[:,:] > 4

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [110]:
# Obtener los valores de la matrix mayor a 4
matrix_b[matrix_b[:,:] > 4]
# Creará una matrix de 1-D

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [111]:
# Obtener los valores de la matrix iguales a 4
matrix_b[matrix_b[:,:] == 4]
# Creará una matrix de 1-D

array([4])

In [114]:
# Obtener los valores de la matrix diferentes de 10
matrix_b[matrix_b[:,:] != 10]
# Creará una matrix de 1-D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15])

In [115]:
# Obtener los valores pares de la matrix
matrix_b[matrix_b[:,:] % 2 == 0]
# Creará una matrix de 1-D

array([ 2,  4,  6,  8, 10, 12, 14])

In [117]:
# Obtener los valores impares mayores de 10
matrix_b[(matrix_b[:,:] % 2 != 0) & (matrix_b[:,:]>10)]
# Creará una matrix de 1-D

array([11, 13, 15])

### Dimensiones y Función Squeeze

In [118]:
# Utilizamos la matrix anteriormente definida
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [119]:
# Función squeeze: Elimina las dimensiones inncesarias de una formación al consultar uno en específico de la matrix

In [121]:
#Obtenemos un array de 2-D
matrix_b[0:1,0:1]

array([[1]])

In [124]:
# Para hacer más legible y comprensible:
print(matrix_b[0:1,0:1].squeeze()) #Nos arroja un simple array, que es un entero

1


### Generar data en Numpy 

### np.empty(), np.zeros(), np.ones(), np.full() 

In [125]:
# np.empty() : crea una matriz vacia de una forma y tipo de dato

In [127]:
# Crear array np.empty()
array_empty = np.empty(shape=(2,3)) #Creamos un ARRAY, con 2 filas y 3 columnas
#Por lo general da un ARRAY de 0, pero en ocasiones con números al azar
array_empty

array([[ 2.,  4.,  5.],
       [ 7.,  8., 10.]])

In [128]:
# np.zeros(): crea una matriz llena de 0 con una forma y tipo de dato

In [131]:
#Crear array np.zeros()
array_zeros=np.zeros(shape=(2,2), dtype=np.int8) #Crea un ARRAY de valores 0 con 2 filas y 2 columnas, con tipo de dato int8
array_zeros

array([[0, 0],
       [0, 0]], dtype=int8)

In [132]:
# np.ines(): crea una matriz llena de 1 con una forma y tipo de dato

In [135]:
#Crear array np.ones()
array_ones=np.ones(shape=(2,4)) # Crea un ARRAY de valores 1 con 2 filas y 4 columnas
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
# np.full(): crea una matriz con una forma dada llena de un valor

In [137]:
#Crear array np.full()
array_full=np.full(shape=(1,2), fill_value=2) # Crea un ARRAY con valores 2, de 1 fila y 2 columnas

### Función "_like" 

In [ ]:
# _like: copia la forma de una matriz

In [139]:
# Definimos un ARRAY de 3-D
matrix_c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix_c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [140]:
# Crear un array np.empty_like tomando la forma de "matrix_c"
array_empty_like= np.empty_like(matrix_c) # Crea un array con las mismas dimensiones y forma, con valores 0 o aleatorios
array_empty_like

array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [   1844,       0,       0, 7077985,       0]])

In [141]:
# Crear un array np.zeros_like tomando la forma de "matrix_c"
array_zeros_like= np.zeros_like(matrix_c) # Crea un array con las mismas dimensiones y forma, con valores 0
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [143]:
# Crear un array np.ones_like tomando la forma de "matrix_c"
array_ones_like= np.ones_like(matrix_c) # Crea un array con las mismas dimensiones y forma, con valores 1
array_ones_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### np.arange() 

In [145]:
# np.arange(): crea una secuencia de valores enteros en un rango dado

In [147]:
#Definimos un ARRAY de un rango de 30
array_rng=np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [149]:
#Definimos un ARRAY de un rango que empieze en 1, termine en 20 y un salto de 2
array_rng=np.arange(start=1, stop=20, step=2, dtype=np.int8)
array_rng

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int8)

### Valores Aleatorios - Random 

In [151]:
# Importamos Generator y PCG64
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [153]:
array_RG = gen(pcg())
array_RG.normal() # Valor aleatoria a partir de distribución normal

-1.740313477873

In [155]:
array_RG = gen(pcg())
array_RG.normal(size=(2,2)) # Valor aleatoria a partir de distribución normal, de 2 filass y 2 columnas

array([[-0.11136972,  0.8953037 ],
       [-0.3275794 , -0.53636655]])

### Generando Enteros, Probabilidades y Opciones Aleatorias 

In [156]:
# numpy.integers(): genera valores enteros

In [159]:
array_RG = gen(pcg(seed=365))
array_RG.integers(15,size=(2,3)) #Genera un ARRAY de enteros aleatorios hasta el 15 de 2 filas y 3 columnas

array([[ 1, 11,  9],
       [11, 12,  9]], dtype=int64)

In [161]:
array_RG = gen(pcg(seed=365))
array_RG.integers(low=15,high=100,size=(2,3)) #Genera un ARRAY de enteros aleatorios desde el 15 hasta el 100 de 2 filas y 3 columnas

array([[23, 79, 66],
       [80, 85, 68]], dtype=int64)

In [ ]:
# numpy.random(): genera valores probabilísticos

In [163]:
array_RG = gen(pcg(seed=365))
array_RG.random(size=(2,3)) #Valores sacados de una distribución uniforme continua (Probabilidad)

array([[0.75915734, 0.7662218 , 0.6291028 ],
       [0.20336599, 0.66501486, 0.06559111]])

In [164]:
# numpy.choice(): simula la idea de hacer una elección arbitraria de una secuencia dada.

In [168]:
array_RG = gen(pcg(seed=365))
array_RG.choice([1,2,3,4,5],size=(2,3)) #valores que se pueden asignar, 2 filas y 3 columnas

array([[1, 4, 4],
       [4, 5, 4]])

### Aplicación de Generación Aleatoria (Random) 

In [169]:
# 1: Cuando no se dispone de datos reales.

In [171]:
# Generar 5 diferentes arays
array_RG = gen(pcg(seed=365))

array_column1=array_RG.normal(loc=2, scale=3, size=(1000))
array_column2=array_RG.normal(loc=7, scale=2, size=(1000))
array_column3=array_RG.logistic(loc=11, scale=3, size=(1000))
array_column4=array_RG.exponential(scale=3, size=(1000))
array_column5=array_RG.geometric(p=0.7, size=(1000))

In [175]:
#Definimos un ARRAY con los arrays definidos antes
# transpose(): transformar filas en columnas
random_test_data=np.array([array_column1,array_column2,array_column3,array_column4,array_column5]).transpose()
random_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  5.18625553,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  4.68270375,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  1.83747938,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.6070154 ,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.37983455,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  3.65112704,  1.        ]])

In [176]:
random_test_data.shape # 5 columnas y 1000 filas

(1000, 5)

In [177]:
# Exportar la data
np.savetxt("Random_test.csv",random_test_data, fmt="%s", delimiter=',') #(nombre_archivo, data, formato, delimitador

In [179]:
# Importar la data
np.genfromtxt("Random_test.csv", delimiter=',') # (nombre_archivo, delimitador)

array([[ 1.59077303,  6.42174295, 10.14698427,  5.18625553,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  4.68270375,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  1.83747938,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.6070154 ,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.37983455,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  3.65112704,  1.        ]])

### Importar y guardar datos con Numpy 

### np.loadtxt() vs. np.genfromtxt()

In [181]:
#Importar data (cargar)
# np.loadtext() : más rápido, pero se rompe al formatear
cargar_data_numeric1=np.loadtxt("D:/data numpy/Lending-Company-Numeric-Data.csv", delimiter=',')
cargar_data_numeric1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [182]:
#Importar data (cargar)
# np.genfromtxt(): más lentro, pero puede manejar valores faltantes
cargar_data_numeric2=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data.csv", delimiter=',')
cargar_data_numeric2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [184]:
# Comprobar que la data sea idéntica
np.array_equal(cargar_data_numeric1,cargar_data_numeric2) # Es idéntico

True

In [188]:
# ARCHIVO CON DATOS FALTANTES (NAN)

In [189]:
#Cargar datos np.loadtxt()
# loadtxt: no se puede cargar por datos faltantes
cargar_data_numeric_NAN=np.loadtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
cargar_data_numeric_NAN

ValueError: could not convert string '' to float64 at row 11, column 4.

In [186]:
#Cargar datos np.genfromtxt() - RECOMENDADO
# Con genfromtxt(), no tenemos problemas
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
cargar_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [190]:
#Cargar datos np.loadtxt()
# loadtxt: para solucionar el problema de carga, definimos un tipo de dato
# Reemplaza los valores faltantes por cadenas vacías
cargar_data_numeric_NAN=np.loadtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", delimiter=';', dtype=np.str)
cargar_data_numeric_NAN

C:\Users\carlo\AppData\Local\Temp\ipykernel_11880\3732940272.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cargar_data_numeric_NAN=np.loadtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", delimiter=';', dtype=np.str)


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

### Limpieza parcial durante la importación 

In [192]:
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
cargar_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [193]:
#Eliminar las primeras 2 filas, util cuando los archivos incluyen líneas de comentarios o notas
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", 
                                      delimiter=';',
                                      skip_header=2) #Eliminar primeras 2 filas
cargar_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [194]:
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", 
                                      delimiter=';',
                                      skip_footer=2) #Eliminar últimas 2 filas
cargar_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [195]:
# Establecer solo columnas queremos utilizar
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", 
                                      delimiter=';',
                                      usecols=(0,1,5)) #Utilizar solo las columnas 0,1 y 5
cargar_data_numeric_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [196]:
# Establecer solo columnas queremos utilizar, estableciendo el orden
cargar_data_numeric_NAN=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", 
                                      delimiter=';',
                                      usecols=(5,1,0)) #Utilizar solo las columnas 5,1,0, se establecerá en el orden especificado
cargar_data_numeric_NAN

array([[13621.,    40.,  2000.],
       [15041.,    40.,  2000.],
       [15340.,    40.,  1000.],
       ...,
       [16600.,    40.,    nan],
       [15600.,    40.,  1000.],
       [16600.,    40.,  2000.]])

In [197]:
# Dividir la data en columnas y definir en variables para su tratamiento
cargar_data_1,cargar_data_2,cargar_data_3=np.genfromtxt("D:/data numpy/Lending-Company-Numeric-Data-NAN.csv", 
                                      delimiter=';',
                                      usecols=(5,1,0),
                                        unpack= True) #Para divir la data

In [199]:
#Consultamos las variables que asignamos los valores
print(cargar_data_1)
print(cargar_data_2)
print(cargar_data_3)

[13621. 15041. 15340. ... 16600. 15600. 16600.]
[40. 40. 40. ... 40. 40. 40.]
[2000. 2000. 1000. ...   nan 1000. 2000.]
